[package]
name = "alfred-numbers-converter"
description = "Alfred Workflow to convert numbers between different bases"
authors = ["Paul Horn <dev@knutwalker.engineer>"]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
powerpack = "0.4.1"
